#super user permissions
sudo: required
language: generic
services:
    - docker

before_install:
    # . is the current directory
    # -t tag
    - docker build -t fanmixco/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true fanmixco/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    #app name
    app: "docker-react"
    env: "DockerReact-env"
    #s3-storage
    bucket_name: "elasticbeanstalk-us-east-2-195243960488"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    #http://dockerreact-env.eba-vk7k8ges.us-east-2.elasticbeanstalk.com/